name: Build LaTeX files

on:
  - push
  - pull_request

jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository and submodules
        uses: actions/checkout@v4
      - name: paper
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: paper
          root_file: main.tex
      - name: poster
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: poster
          root_file: main.tex
          texlive_version: 2023
